apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: DATABASE_URI
          valueFrom:
            configMapKeyRef:
              name: {{ include "backend.fullname" . }}-config
              key: DATABASE_URI
        resources: 
          {{- toYaml .Values.resources | nindent 12 }}
        
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
