
replicaCount: 1

image:
  repository: dev126712/dockerized-three-tier-app-database
  pullPolicy: IfNotPresent
  tag: "d85e9675297521ee1646fcec0b553d0e2ec7f6b8"

auth:
  rootUsername: "admin"
  rootPassword: "pass"
  database: "mydatabase"


podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  capabilities:
    drop:
     - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 27017
  targetPort: 27017

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: gateway
    sectionName: http.
  hostnames:
  - chart-example.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers

livenessProbe:
  tcpSocket:
    port: 27017
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 27017
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false

volumes: 
  - name: mongo-data
    mountPath: /data/db

volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
