#global:
#  namespace: 3t-app
#
#replicaCount: 1
#
#image:
#  repository: dev126712/dockerized-three-tier-app-backend
#  pullPolicy: IfNotPresent
#  tag: "4dbf24891156fa946e9148ac9ad71b011f713658"

# Mapped from your Service manifest
#service:
#  type: ClusterIP
#  port: 8080 

# Mapped from your Deployment resources
#resources:
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  limits:
#    cpu: 200m
#    memory: 256Mi

# Mapped from your HPA manifest
#autoscaling:
#  enabled: true
#  minReplicas: 1
#  maxReplicas: 2
#  targetCPUUtilizationPercentage: 60

# Custom section for your ConfigMap data
#configData:
#  DATABASE_URI: "mongodb://admin:pass@database-service.3t-app.svc.cluster.local:27017/mydatabase?authSource=admin"

# Deployment Strategy (Add this to your deployment template if not present)
#strategy:
#  rollingUpdate:
#    maxSurge: 2
#    maxUnavailable: 1

#securityContext:
#  capabilities:
#    drop:
#    - ALL
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 1000

