apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
spec:
  data:
    datasource.yaml: |-
      apiVersion: 1
      datasources:
      - name: VictoriaMetrics
        type: prometheus
        url: http://victoria-metrics.monitoring.svc:8428
        access: proxy
        isDefault: true
        updateIntervalSeconds: 10
        editable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: datasource-config
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: datasource-config
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000 # Access via http://<node-ip>:32000
  selector:
    app: grafana
