namespace: 3t-app-dev

frontend:
  global:
  namespace: 3t-app-dev

  frontend:
    replicaCount: 1
    image:
      repository: dev126712/dockerized-three-tier-app-frontend
      tag: "d85e9675297521ee1646fcec0b553d0e2ec7f6b8"
      pullPolicy: IfNotPresent
    service:
      annotations: {}
      type: NodePort
      port: 80
      targetPort: 8000
    ingress:
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - host: dev.chart-example.local
          paths:
            - path: /api
              pathType: Prefix
              backendService: three-tier-app-backend-service 
              backendPort: 8080
            - path: /
              pathType: Prefix
              backendService: three-tier-app-frontend-service
              backendPort: 80
              
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    autoscaling:
      enabled: false




  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: 
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  service:
    annotations: {}  # This "empty map" tells Helm the key exists but has no data
    type: NodePort
    port: 80
    targetPort: 8000
    protocol: TCP

  #ingress:
  #  className: "nginx"
  #  annotations:
  #    nginx.ingress.kubernetes.io/rewrite-target: /
  #  hosts:
  #    - host: chart-example.local
  #      paths:
  #        - path: /api
  #          pathType: Prefix
  #          backendService: backend-service
  #          backendPort: 8080
  #        - path: /
  #          pathType: Prefix
  #          backendService: frontend-service
  #          backendPort: 80
  #  tls: []

  ingress:
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: dev.chart-example.local
        paths:
          - path: /api
            pathType: Prefix
            # FIX: This must match the full name of your backend service
            backendService: three-tier-app-backend-service 
            backendPort: 8080
          - path: /
            pathType: Prefix
            # FIX: This must match the full name of your frontend service
            backendService: three-tier-app-frontend-service
            backendPort: 80




  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
  volumes: []
  volumeMounts: []
  nodeSelector: {}

  tolerations: []

  affinity: {}

  service:
    type: NodePort










backend:
  global:
  namespace: 3t-app-dev

  replicaCount: 1

  image:
    repository: dev126712/dockerized-three-tier-app-backend
    pullPolicy: IfNotPresent
    tag: "801b80920334515356715c23caaf57bdd11779f8"

  # Mapped from your Service manifest
  service:
    type: ClusterIP
    port: 8080 

  # Mapped from your Deployment resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Mapped from your HPA manifest
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 60

  # Custom section for your ConfigMap data
  configData:
    DATABASE_URI: "mongodb://admin:pass@database-service.3t-app-dev.svc.cluster.local:27017/mydatabase?authSource=admin"

  # Deployment Strategy (Add this to your deployment template if not present)
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000


  service:
    type: ClusterIP











database:
  global:
  namespace: 3t-app-dev

  replicaCount: 1

  image:
    repository: dev126712/dockerized-three-tier-app-database
    pullPolicy: IfNotPresent
    tag: "d85e9675297521ee1646fcec0b553d0e2ec7f6b8"

  auth:
    rootUsername: "admin"
    rootPassword: "pass"
    database: "mydatabase"


  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    readOnlyRootFilesystem: true # Keep this for security
    runAsNonRoot: true
    runAsUser: 1000

  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  httpRoute:
    enabled: false
    annotations: {}
    parentRefs:
    - name: gateway
      sectionName: http.
    hostnames:
    - chart-example.local
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /headers

  livenessProbe:
    tcpSocket:
      port: 27017
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    tcpSocket:
      port: 27017
    initialDelaySeconds: 5
    periodSeconds: 10

  autoscaling:
    enabled: false

  volumes:
    - name: tmp-volume
      emptyDir: {}

  volumeMounts:
    - name: mongo-data
      mountPath: /data/db
    - name: tmp-volume
      mountPath: /tmp

  volumeClaimTemplates: 
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  serviceAccount:
    create: false
    name: ""
    annotations: {}

  service:
    type: ClusterIP
