apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: 3t-app
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: DATABASE_URI
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_URI
        resources: 
          {{- toYaml .Values.resources | nindent 12 }}
